### ISSUE TITLE
Drizzle & Ledger used together crashes Ganache

### ISSUE THREAD

**Issue by joshma91** [trufflesuite/ganache-cli#589]
When integrating Ledger functionality into Drizzle, Ganache errors out once a new block is mined. This doesn't occur if only Ledger or Drizzle is independently used with Ganache.
```
TypeError: Cannot read property 'connection' of undefined
    at c._updateSubscriptions (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:65:5443)
    at l.<anonymous> (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:65:3860)
    at emitTwo (events.js:126:13)
    at l.emit (events.js:214:7)
    at o.<anonymous> (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:37:29806)
    at emitTwo (events.js:126:13)
    at o.emit (events.js:214:7)
    at o._notificationHandler (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:149:96040)
    at Array.forEach (<anonymous>)
    at s.<anonymous> (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:149:95544)
    at emitOne (events.js:116:13)
    at s.emit (events.js:211:7)
    at s.update (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:149:93395)
    at emitOne (events.js:121:20)
    at s.emit (events.js:211:7)
    at s._setCurrentBlock (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:149:225524)
    at n.a._blockTracker.on.e (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:149:224128)
    at emitOne (events.js:121:20)
    at n.emit (events.js:211:7)
    at n._setCurrentBlock (/home/josh/.npm-packages/lib/node_modules/ganache-cli/build/cli.node.js:65:7618)
    at emitOne (events.js:116:13)
    at g.emit (events.js:211:7)
```
## Expected Behavior
I expect a new block to be mined without Ganache crashing.

## Current Behavior
Upon mining a new block with a Ledger device plugged in and providing its web3 to Drizzle, Ganache crashes.

## Possible Solution
Ganache works perfectly with Drizzle and Ledger independently. It's only when all three are used in conjunction that this error arises. I use the following code in my modified Drizzle module (in `web3Saga.js`) to grab web3 from my Ledger (adapted from this [guide](https://gist.github.com/gre/93fc39242c31a23c0570e71cc33bed5a)):

```javascript
const result = yield eth.getAddress("m/44'/60'/0'/0/0")
if (result !== null) {
  const engine = new ProviderEngine()
  const getTransport = () => Transport.create()
  const ledger = createLedgerSubprovider(getTransport, {
    networkId,
    accountsLength: 5
  })
  console.log(ledger)
  engine.addProvider(ledger)
  engine.addProvider(new FetchSubprovider({ rpcUrl }))
  engine.start()
  return new Web3(engine)
}
```
If I set a really long blocktime, I'm able to access the web3 instance and can sign transactions using my Ledger in my DApp. It's only when the next block is mined that the error occurs.  

## Steps to Reproduce (for bugs)
This is a long one as reproduction requires modification of the Drizzle module, so please bear with me.

1. Follow installation and setup instructions here: https://github.com/truffle-box/drizzle-box.
Run ganache-cli with `ganache-cli -b 3 --networkId 1337`   and migrate contracts as explained in the instructions.
2. Uninstall Drizzle and replace with custom Drizzle with Ledger integration
  a. run `npm uninstall drizzle`
  b. clone/fork the [Drizzle](https://github.com/trufflesuite/drizzle/) repo into another folder
  c. replace `web3Saga.js` with the contents of this [gist](https://gist.github.com/joshma91/bd39fb834b935aa7328a3c3396b1ca29) 
  d. run `npm install @ledgerhq/hw-transport-u2f @ledgerhq/web3-subprovider @ledgerhq/hw-app-eth web3-provider-engine` in the root of the cloned Drizzle project
  e. run `npm link`
  f.  navigate to the root directory of the Drizzle Box and run `npm link drizzle`  
  g. in `package.json` change the `start` script to: `HTTPS=true node scripts/start.js`
3. Plug your Ledger into your computer, unlock it, and navigate to the Ethereum app, ensuring that 'contract data' and 'browser support' are enabled 
4. Because of another issue, you have to go into `src/index.js` in Drizzle Box and include `
import 'babel-polyfill'`. Also `npm install babel-polyfill`
5. Run `npm run start` 
5. Observe ganache-cli error when it mines a new block

GIF of error (note that the web3 instance is logged in the console on load, and then after a few seconds after loading, Ganache in the top right terminal window errors out) 
![ezgif com-optimize 2](https://user-images.githubusercontent.com/9612111/48321107-e0ac0f00-e5d4-11e8-87b1-c6a9499391d8.gif)

## Context
I was working on this Drizzle [issue](https://github.com/trufflesuite/drizzle/issues/137) to have Drizzle support Ledger. This Ganache issue is blocking my progress on that end. 

I don't entirely understand why these downstream consumers (the DApp and Drizzle) are causing Ganache to crash. I'd appreciate it someone can shed some light onto this issue. Because of how many moving parts are involved, I realize this might be an edge case that doesn't warrant immediate attention, but thanks for reading through all this anyway!

## Your Environment
Ubuntu 18.04
Drizzle Box & modified Drizzle current as of today: Nov 11, 2018
NodeJS Version: 8.11.3
Ganache CLI v6.1.8 (ganache-core: 2.2.1)

**Comment by benjamincburns** [comment]
@joshma91 thanks for the detailed writeup! Does this reproduce under `ganache-cli` v6.2.x?
