### ISSUE TITLE
Corrupted signature or message sometimes leads to invalid nonce error

### ISSUE THREAD

**Issue by webmaster128** [trufflesuite/ganache-cli#621]
How to reproduce:

1. Start a new instance of ganache-cli (v6.2.5/docker)
2. Use account `A` from the auto-generated accounts with funds 
3. Send some valid transactions to the blockchain
4. Query latest nonce, send an ETH send transaction with (a) corrupted signature or (b) corrupted data field

Instead of a "invalid signature" message this leads to:

```json
{
  "code": -32000,
  "message": "the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 14",
  "data": {
    "stack": "n: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 14\n    at i (/app/ganache-core.docker.cli.js:37:300962)\n    at blockchain.getQueuedNonce (/app/ganache-core.docker.cli.js:37:301093)\n    at /app/ganache-core.docker.cli.js:25:150975\n    at /app/ganache-core.docker.cli.js:37:630596\n    at /app/ganache-core.docker.cli.js:37:634357\n    at Object.return (/app/ganache-core.docker.cli.js:37:633934)\n    at /app/ganache-core.docker.cli.js:37:632186\n    at e (/app/ganache-core.docker.cli.js:37:634305)\n    at /app/ganache-core.docker.cli.js:37:634316\n    at /app/ganache-core.docker.cli.js:37:631398\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "name": "n"
  }
}
```

However, there is probably a race condition involved since sometimes instead I get

```
{
  "code": -32000,
  "message": "Invalid Signature",
  "data": {
    "stack": "Error: Invalid Signature\n    at e.getSenderPublicKey (/app/ganache-core.docker.cli.js:10:88137)\n    at e.getSenderAddress (/app/ganache-core.docker.cli.js:10:87941)\n    at A.queueRawTransaction (/app/ganache-core.docker.cli.js:37:292154)\n    at u.eth_sendRawTransaction (/app/ganache-core.docker.cli.js:37:283039)\n    at u.handleRequest (/app/ganache-core.docker.cli.js:37:280006)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at a.handleRequest (/app/ganache-core.docker.cli.js:37:278371)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at s.f.handleRequest (/app/ganache-core.docker.cli.js:37:271502)\n    at s.handleRequest (/app/ganache-core.docker.cli.js:37:269329)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at c.handleRequest (/app/ganache-core.docker.cli.js:37:277385)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at a.handleRequest (/app/ganache-core.docker.cli.js:37:276832)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at d._handleAsync (/app/ganache-core.docker.cli.js:37:143403)\n    at Timeout._onTimeout (/app/ganache-core.docker.cli.js:37:142828)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)",
    "name": "Error"
  }
}
```

The ratio _incorrect nonce_ to _invalid signature_ is about half half.

I suspect the following: the sender is calculated from signature+message via the secp256k1 public key recovery algorithm. Now before the signature is checked for validity, the nonce is compared to the nonce of a wrong account `B != A`.

On Rinkeby I observe the same problem. They just report `{"code":-32000,"message":"invalid sender"}` which is a little bit less confusing but still not great.

**Comment by davidmurdoch** [comment]
Thanks for filing this issue, @webmaster128. Can you provide an example of how you generate the transaction with an invalid signature?

**Comment by webmaster128** [comment]
Sure, I try to explain how to reproduce as good as possible. I use [IOV-Core](https://github.com/iov-one/iov-core/) to interact with Ethereum as well as create and ETH send transactions. IOV-Core is a higher level abstration layer that can connect to multiple blockchains. The ethereum connection is [this folder](https://github.com/iov-one/iov-core/tree/master/packages/iov-ethereum), or most specifically [ethereumconnection.ts](https://github.com/iov-one/iov-core/blob/master/packages/iov-ethereum/src/ethereumconnection.ts). In the associated tests, [we test all kind of ETH send transactions](https://github.com/iov-one/iov-core/blob/v0.11.2/packages/iov-ethereum/src/ethereumconnection.spec.ts#L290-L463). Every `SendTransaction` is encoded into Ethereum RLP binary [using serialization.ts](https://github.com/iov-one/iov-core/blob/v0.11.2/packages/iov-ethereum/src/serialization.ts#L13-L43).

This all works very nicely for correctly signed transactions with Ganache, Ropsten and Rinkeby.

Now [we try testing corrupted transactions](https://github.com/iov-one/iov-core/blob/v0.11.2/packages/iov-ethereum/src/ethereumconnection.spec.ts#L432), where we

- (a) [corrupt the signature](https://github.com/iov-one/iov-core/blob/v0.11.2/packages/iov-ethereum/src/ethereumconnection.spec.ts#L452) by flipping 1 bit of the highest byte of the signatures `s`
- (b) leave the signature untouched and [corrupt the message by appending a trailing "!"](https://github.com/iov-one/iov-core/blob/v0.11.2/packages/iov-ethereum/src/ethereumconnection.spec.ts#L453-L454) to the transaction's memo/data field.

I'm sure you can reproduce the same behaviour using plain Ethereum tooling, which unfortunatly I don't have right now. In oder to reproduce using IOV-Core, the steps are:

1. Clone repo
2. `yarn install && yarn build`
3. Start ganache using docker: `./scripts/ethereum/start.sh`
4. `export ETHEREUM_ENABLED=1`
5. `cd packages/iov-ethereum`
6. `yarn test`: all green
7.  un-exclude test "reports error for invalid signature" from src/ethereumconnection.spec.ts
8. `yarn test`: error (sometimes, as described above)

I hope this helps. Otherwise I'm here to support further debugging.
