### ISSUE TITLE
Ganache throws `ECONNREFUSED` error and shuts down abruptly when account balance reaches or exceeds 2 ^256 wei

### ISSUE THREAD

**Issue by barakman** [trufflesuite/ganache-cli#626]
Ganache throws `ECONNREFUSED` error and shuts down abruptly when account balance reaches or exceeds 2 ^256 wei.

## Steps to Reproduce (for bugs)

File MyContract.sol:
```
pragma solidity 0.4.25;

contract MyContract {
    uint public balance;
    uint public value;
    function deposit() external payable {
        balance = address(this).balance;
        value = msg.value;
    }
}
```
File MyTest.js:
```
contract("MyTest", function(accounts) {
    it("test", async function() {
        const myContract = await artifacts.require("MyContract").new();
        await myContract.deposit({from: accounts[0], value: web3.toBigNumber(2).pow(255)});
        const balance1 = await myContract.balance();
        const value1   = await myContract.value  ();
        console.log();
        console.log(balance1.toFixed());
        console.log(value1  .toFixed());
        await myContract.deposit({from: accounts[1], value: web3.toBigNumber(2).pow(255).plus(1)});
        const balance2 = await myContract.balance();
        const value2   = await myContract.value  ();
        console.log();
        console.log(balance2.toFixed());
        console.log(value2  .toFixed());
    });
});
```
Ganache command-line:
```
ganache-cli --port=8545 --gasPrice=20000000000 --gasLimit=8000000
    --account=0x0000000000000000000000000000000000000000000000000000000000000001,0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    --account=0x0000000000000000000000000000000000000000000000000000000000000002,0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
Truffle configuration:
```
        development: {
            host:       "127.0.0.1",
            port:       8545,
            network_id: "*",
            gasPrice:   100000000000,
            gas:        8000000
        }
```
## Output:
```
    Contract: MyTest test:
57896044618658097711785492504343953926634992332820282019728792003956564819968
57896044618658097711785492504343953926634992332820282019728792003956564819968
  1) Contract: MyTest test
  2) Contract: MyTest "after each" hook: after test for "test"

  0 passing (2s)
  2 failing

  1) Contract: MyTest
       test:
     Error: Invalid JSON RPC response: "Error: read ECONNRESET\n    at _errnoException (util.js:992:11)\n    at TCP.onread (net.js:618:25)"
      at ProviderError.ExtendableError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-error\index.js:10:1)
      at new ProviderError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\error.js:17:1)
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:71:1
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:129:1
      at exports.XMLHttpRequest.request.onreadystatechange (C:\...\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at exports.XMLHttpRequest.dispatchEvent (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:591:1)
      at setState (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:610:1)
      at exports.XMLHttpRequest.handleError (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:532:1)
      at ClientRequest.errorHandler (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:459:1)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: MyTest
       "after each" hook: after test for "test":
     Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n    at Object._errnoException (util.js:992:11)\n    at _exceptionWithHostPort (util.js:1014:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)"
      at ProviderError.ExtendableError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-error\index.js:10:1)
      at new ProviderError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\error.js:17:1)
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:71:1
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:129:1
      at exports.XMLHttpRequest.request.onreadystatechange (C:\...\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at exports.XMLHttpRequest.dispatchEvent (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:591:1)
      at setState (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:610:1)
      at exports.XMLHttpRequest.handleError (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:532:1)
      at ClientRequest.errorHandler (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:459:1)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
## Environment:
- truffle v4.1.15
- ganache-cli v6.2.5
- node v8.11.2
- npm v6.4.1
- Windows 10

**Comment by davidmurdoch** [comment]
An odd edge case you've got here, @barakman!

These notes are mostly for the Ganache team. If you are curious as to why this fails read on!

The maximum `account(this).balance` value allowed by solidity (I haven't checked the yellow paper definition itself) is the max value of `uint256`, which is `2**256 - 1`; this is the largest number that can fit in *32 bytes*.

What the contract and tests above are (attempting) to do is
* increase the balance of the contract to beyond the limits the data type backing `address(this).balance` (`uin256`).
  * this actually seems to be allowed by the ethereumjs-vm, it probably shouldn't work.
* increase the _stored_ value of balance
  * this actually seems to be allowed by the ethereumjs-vm, it probably shouldn't work.
  * this line is probably to blame: https://github.com/ethereumjs/ethereumjs-vm/blob/0162d471957a1a31663b64eac7f14bff5a8e29f6/lib/vm/opFns.js#L540 It should probably be limiting the size of the value? Not really sure though.
* read this balance value from the contract's storage
  * this doesn't work. When reading the value out of storage the `MSTORE` opcode is called, and this opcode _does_ require that the size of the resulting `Buffer` is 32 bytes: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/vm/opFns.js#L497

Because the `BN.toArrayLike` method throws (https://github.com/indutny/bn.js/blob/24cc2dd51b58694088a637a314689f61c9ba65a4/lib/bn.js#L546) when the size of the BN is larger than allowed, and the VM doesn't catch the exception, this error bubbles up to ganache-core, which also doesn't catch the exception (though this is intentional as we don't want to mask potential flaws in the VM implementation).

**Comment by davidmurdoch** [comment]
Opened https://github.com/ethereumjs/ethereumjs-vm/issues/464 at the VM to see if they can figure this one out. Thanks again for filing the issue, @barakman.

**Comment by davidmurdoch** [comment]
Branch with a failing test: https://github.com/trufflesuite/ganache-core/tree/contract-storage-overflow

**Comment by davidmurdoch** [comment]
Failing test case: https://github.com/trufflesuite/ganache-core/blob/a62740aff7a8910e2936e1d891fd799cd6fc6477/test/contract-storage.js#L53-L54

Branch: https://github.com/trufflesuite/ganache-core/tree/contract-storage-overflow

**Comment by barakman** [comment]
@davidmurdoch:
Thank you for handling it.

My initial goal (knowing that the maximum balance is `2**256-1`) was to check if the expression `msg.value > address(this).balance` could ever hold.

It could theoretically hold, when a contract's balance overflows as a result of sending funds to the contract.

So I was trying to see if the EVM would allow this to take place.

Of course, if Ganache doesn't emulate the EVM correctly at this "singularity point", then the test described above will not satisfy my goal in any case.

Thanks again :)

**Comment by davidmurdoch** [comment]
Interesting. From quick glance at the geth source code it doesn't look like there are any limits for the maximum balance of an address (https://github.com/ethereum/go-ethereum/blob/ee92bc537f159c2202058a33e015684cc2bca04c/core/state/state_object.go#L272). With that said, I'm not familiar with Golang or Geth internals and could be looking in the wrong place.

**Comment by barakman** [comment]
Hmmm... I guess I could try this with geth, after setting up a private network and an account with almost `2**256` wei. Will get back to you on that one. Thanks.
