### ISSUE TITLE
Truffle debug `TypeError: Cannot read property 'id' of undefined`

### ISSUE THREAD

**Issue by isaacsultan** [trufflesuite/ganache-cli#630]
## Issue

Receiving `TypeError: Cannot read property 'id' of undefined` whenever truffle `debug` is used with `ganache-cli`

NB: the string 'id' does not appear anywhere in my `.sol` contract or `.js` unit test that produced the transaction.

## Steps to Reproduce

```
truffle debug 0xa1e863b7859a74ab256060bcba215f8669f57fc932c00971b44450000160c387
```

## Actual Results

```
Gathering transaction data...

TypeError: Cannot read property 'id' of undefined
    at newScope.variables.concat.filter.variable (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1738:1)
    at Array.filter (<anonymous>)
    at map (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1735:1)
    at Array.map (<anonymous>)
    at data.info.scopes._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1720:125)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at Function._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at args (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at Function._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at args (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at runSelectEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:723:1)
    at runEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1191:1)
    at digestEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1258:1)
    at next (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1148:1)
    at currCb (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at checkEnd (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-585b854f.js:154:1)
    at chCbAtKey (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-585b854f.js:170:1)
    at Object.currCb [as cont] (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at end (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1001:1)
    at Object.task.cont (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:829:1)
    at next (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1157:1)
    at Object.currCb [as cont] (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at end (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1001:1)
The above error occurred in task session.saga
Tasks cancelled due to error:
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga
```

## Environment

* Operating System: macOS
* Ethereum client: ganache0-cli
* Truffle version: Truffle v5.0.0 
* node version: v8.9.3
* npm version: 6.5.0

**Comment by davidmurdoch** [comment]
@haltman-at is this error message one that you are familiar with?

**Comment by haltman-at** [comment]
It is not!  Thanks for pointing this out, I'll have to take a look.  This certainly looks like a debugger issue rather than a ganache-cli issue, though.

**Comment by haltman-at** [comment]
I'll probably need more reproduction info to figure out what's going on, I should note.  Just looking through the code, I don't know why this would happen.

**Comment by davidmurdoch** [comment]
@isaacsultan 	This error message is coming from `truffle`, so I'll move the issue to that repo so it can be properly triaged there.
