### ISSUE TITLE
6.4.2: `TypeError: Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by tyler17** [trufflesuite/ganache-cli#641]
## Expected Behavior
ganache-cli not crashing
## Current Behavior
After upgrading to v6.4.2 (from v6.2.5), the testchain will randomly crash in the middle of our tests with 
```
eth_blockNumber
eth_blockNumber
eth_blockNumber
TypeError: Cannot read property '0' of undefined
    at e (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5393)
    at u (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5429)
    at u (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5955)
    at u (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5770)
    at /Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:4169
    at /Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1861552
    at /Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124
    at i (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:41179)
```

## Steps to Reproduce
checkout branch `sdk-688` here: https://github.com/makerdao/dai.js/tree/sdk-688
follow steps under `Developing` in Readme
run tests with `yarn test`

## Your Environment
* Version used: 6.4.2
* NodeJS Version: v10.13.0
* Operating System and version: macOS High Sierra, version 10.13.4 Beta
* Link to your project or repro gist: https://github.com/makerdao/dai.js/tree/sdk-688
* Commit hash to use with above link for reproduction: 7a246d18b91f259bb9e3f9ec1a064fba96ab9619

**Comment by ndeshev** [comment]
I can confirm that this problem exists, it also makes using ganache-cli with MetaMask impossible, as it crashes everytime a transaction has to be signed, so I had to switch back to version 6.4.1. 

The problem is related to the new  "gas exactimation" methods used in versions > 6.4.1

**Comment by davidmurdoch** [comment]
Thanks @tyler17 for the report. I'll try to get a hotfix release out for this today!

**Comment by davidmurdoch** [comment]
@ndeshev, what leads you to believe this crash is gas estimation related? Can you add some log output here? (starting ganache-cli with the `--verbose` flag would be extra helpful)

**Comment by ndeshev** [comment]
David, yes, I tested it with the verbose option on. Also the contracts passed about 200 unit tests in Truffle where I never estimate gas usage and the only time the ganache-cli breaks with `TypeError: Cannot read property '0' of undefined` error is when a link to a contract function is clicked and the MetaMask transaction sign window has to pop up with the gas price and the total cost of the transaction.

The estimated gas for the transaction that the MetaMask is displaying is almost the maximum I set for allowed for block gas limit. If I leave the MetaMask transaction window open and restart the ganache-cli it sends it successfully. 

Also, the problem did not exist in versions lower than 6.4.1 which is another thing that led me to think is gas estimation problem related as this was one of the few changes in versions 6.4.2 and 6.4.3.

Note: I did some more testing, there are function that did not break the ganache client when MetaMask is invoked, but there are very simple short ones, on calls to more complicated functions the problem persists. 

Logs:

eth_blockNumber
   > {
   >   "id": 1333707413168176,
   >   "jsonrpc": "2.0",
   >   "params": [],
   >   "method": "eth_blockNumber"
   > }
 <   {
 <     "id": 5050169228901374,
 <     "jsonrpc": "2.0",
 <     "result": "0x1e43"
 <   }
 <   {
 <     "id": 1333707413168176,
 <     "jsonrpc": "2.0",
 <     "result": "0x1e43"
 <   }
eth_estimateGas
   > {
   >   "id": 4525324431062,
   >   "jsonrpc": "2.0",
   >   "params": [
   >     {
   >       "from": "0x2b235b23be383bfd75d87f865f6fb74536072f57",
   >       "to": "0x81e86b03500da6377478272f2dcde68e33ec360a",
   >       "value": "0x3bf3b91c95b00000",
   >       "data": "0xbaaa1ea8000000000000000000000000000000000000000000000000000000000000000500000000000000000000000018c6a286552899dc9d74b3dbd3dc26bf80d277a1",
   >       "gasPrice": "0x4a817c800",
   >       "gas": "0x657890"
   >     }
   >   ],
   >   "method": "eth_estimateGas"
   > }
TypeError: Cannot read property '0' of undefined
    at e (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:69:5393)
    at u (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:69:5429)
    at u (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:69:5955)
    at u (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:69:5770)
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:69:4169
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:61:1853218
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26124
    at i (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:41179)
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:61:1210468
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:105466
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:32:392
    at c (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:32:5407)
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:32:317
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:61:1871644
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:23237
    at o (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26646)
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26124
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:61:1864681
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:61:1862544
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:61:1889757
    at C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:23237
    at o (C:\Users\ndesh\AppData\Roaming\npm\node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26646)

**Comment by davidmurdoch** [comment]
@ndeshev we found a potential fix, but can't pinpoint the contract that causes the condition that triggers the bug. Can you share with us the contract and method(s) that are causing the crash?
