### ISSUE TITLE
REVERT opcode in factory pattern when using a forked chain

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/ganache-cli#652]
When working with a forked chain, transactions that create a contract and call a function of the newly created contract are REVERTED. 

## Expected Behavior
Such transactions execute successfully on a **non-forked** `ganache-cli` instance or on the target chain (goerli or mainnet). They should behave the same on a forked ganache chain.

## Current Behavior
Transaction REVERT's with
```
Error: Returned error: VM Exception while processing transaction: revert
    at XMLHttpRequest._onHttpResponseEnd (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at /Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
    at Object.ErrorResponse (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1)
```

Transaction details output from running `ganache-cli` fork in verbose mode:

```
eth_sendTransaction
   > {
   >   "jsonrpc": "2.0",
   >   "id": 9,
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "from": "0x7afb67a48c6a3e5c15a36454a6e7602dbcdd3b5f",
   >       "gas": "0x6691b7",
   >       "to": "0x79073fc2117dd054fcedacad1e7018c9cbe3ec0b",
   >       "data": "0x08eb0d2c000000000000000000000000d468b86abb0c58f0b948b36a8769829abd66d8af",
   >       "gasPrice": "0x4a817c800"
   >     }
   >   ]
   > }
 <   {
 <     "id": 9,
 <     "jsonrpc": "2.0",
 <     "result": "0x4c7878844a77133d9fbaebfeabb59f7e2b952f0531dc3344ac51b78556536d3b",
 <     "error": {
 <       "message": "VM Exception while processing transaction: revert",
 <       "code": -32000,
 <       "data": {
 <         "0x4c7878844a77133d9fbaebfeabb59f7e2b952f0531dc3344ac51b78556536d3b": {
 <           "error": "revert",
 <           "program_counter": 297,
 <           "return": "0x"
 <         },
 <         "stack": "o: VM Exception while processing transaction: revert\n    at Function.o.fromResults (/Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:81931)\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:115772\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:96183\n    at p (/Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:95840)\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:95893\n    at t.default (/Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:475253)\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:96807\n    at w.n.emit (/Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1211582)\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1850380\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1850403\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:500010\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26262\n    at i (/Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:41317)\n    at /Users/Elena/colonyNetwork/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:21785\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
 <         "name": "o"
 <       }
 <     }
 <   }
``` 
## Possible Solution
Although this issue bears resemblance to https://github.com/trufflesuite/ganache-cli/issues/646 , testing the failing transactions with passing the max gas (using `{ gas: '0x6691b7' }`) doesn't produce different results.

We have also tested whether this is a regression bug introduced in the recent `--fork` logic fixes. However the issue persists with all of the following `ganache-cli` versions going back to January this year:
`6.4.4-beta.0`
`6.4.3`
`6.4.3-beta.0`
`6.4.2`
`6.4.0`
`6.3.0`

## Steps to Reproduce (for bugs)
To reproduce against a `goerli` fork run the following in a `truffle console` after forking the chain:
```
const colonyNetwork = await IColonyNetwork.at("0x79073fc2117dD054FCEdaCad1E7018C9CbE3ec0B")

await colonyNetwork.createColony("0xD468b86aBB0C58F0B948b36a8769829aBD66d8AF")
Error: Returned error: VM Exception while processing transaction: revert
    at XMLHttpRequest._onHttpResponseEnd 
```
The `createColony` call is one of the few factory methods we use to instantiate a new Colony in the network. The others are `initialiseReputationMining` and `startNetCycle` methods on `IColonyNetwork` which exhibit the same behaviour. You'll need the `IColonyNetwork` build artefact from https://github.com/JoinColony/colonyNetwork/tree/develop/contracts

## Context
We are currently blocked and unable to test key areas of functionality in the Colony Network on testnet and mainnet. Also it blocks any regression testing we can do on new functionality and fixes. Basically it blocks our go-live.

## Your Environment
* Version used: 6.4.3
* Version of Truffle/Remix/Other tools used: 
Truffle v5.0.18 (core: 5.0.18)
Solidity - 0.5.8 (solc-js)
Node v10.12.0
Web3.js v1.0.0-beta.37
* Operating System and version (include distro if Linux): OSX
* Link to your project or repro gist: https://github.com/JoinColony/colonyNetwork
* Commit hash to use with above link for reproduction: `latest`

**Comment by niklasb** [comment]
This could be caused by #653, if the contract performs a `SSTORE` of value 0 (you could check by running ganache in --debug mode).

**Comment by elenadimitrova** [comment]
@niklasb as per your suggestion I tested the reproduction steps above against a `goerli` forked instance running in debug mode, results [here](https://gist.github.com/elenadimitrova/0caa798e552b3b026a3a19258e93ecba)
I ran the same test against a local `ganache-cli` which produced some very different results, so I'm uncertain it's of any use for troubleshooting but still, it is [here](https://gist.github.com/elenadimitrova/b7781677a7f6cf4635169e81bf756181).

I am happy to test your suggestion of the `SSTORE 0` operation with our test case, do you have a branch I can install your suggested fix from?

**Comment by niklasb** [comment]
I don’t have a proper fix for this, other than the very dirty hack I posted in the other issue.

**Comment by elenadimitrova** [comment]
I just tested that hack and no difference in the opcodes emitted. See the diff with [revised gist compared to the original one](https://gist.github.com/elenadimitrova/0caa798e552b3b026a3a19258e93ecba/revisions).

**Comment by elenadimitrova** [comment]
Sharing some extra findings here. 
As @niklasb  pointed out the `SSTORE 0x0` operation is not completing. We have a function suitable for testing this which is the `IReputationMiningCycle.confirmNewHash` where [this](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetworkMining.sol#L76) isn't completed but transaction continues, only to fail on [this](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetworkMining.sol#L99) check which simply ensures that previous `SSTORE 0x0` is completed correctly.

This was confirmed by a second function failure: `OneTxPaymentFactory.removeExtension` which also isn't completing correctly.

This only appears to be a problem if the `SSTORE` operation setting the slot from zero no non-zero was completed on the _origin_  `ganache-cli` instance. If `SSTORE` was done on fork, setting that slot from non-zero to zero worked correctly. 

There is something else which is broken as even when I instantiate the entire Network setup on fork, transactions which create contracts still fail.

**Comment by elenadimitrova** [comment]
There is a problem with calls to contracts created in the context of the call. Their addresses are valid but they appear empty, we see this in the debug log of a failed `createColony`
```
EXTCODESIZE 0x2aafd0f1cc1c47a52affbc1f805f7da45b591e44
ISZERO 0x0
```
vs a successful one
```
EXTCODESIZE 0xa0e9a5781b26d9450d5e1d53abb3da887a67d7f
ISZERO 0x554
```

**Comment by niklasb** [comment]
I have personally also run into your second issue. I filed an issue for this at https://github.com/trufflesuite/ganache-core/issues/454 @davidmurdoch which includes a minimal reproducer.
