### ISSUE TITLE
Ganache/Mocha String Error Issue

### ISSUE THREAD

**Issue by aakilfernandes** [trufflesuite/ganache-cli#658]
Somewhere in ganache-cli (hard to tell where cause the error is a build) there's an error being thrown thats a string. Usually this would just propogate and give an easy string message, but mocha can't handle string errors (it attempts to add a property that causes it to break).

```
TypeError: Cannot create property 'uncaught' on string 'abort({"message":"FailedTransaction: VM Exception while processing transaction: revert","error":{},"stack":"Error\n    at new FailedTransaction (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/testable-error/index.js:4:18)\n    at batch.parts.forEach (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ultralightbeam/lib/execute.js:52:35)\n    at Array.forEach (<anonymous>)\n    at ultralightbeam.provider.sendAsync (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ultralightbeam/lib/execute.js:41:17)\n    at process.nextTick (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:80089)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}). Build with -s ASSERTIONS=1 for more info.'
    at Runner.uncaught (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/mocha/lib/runner.js:730:16)
    at process.uncaught (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/mocha/lib/runner.js:843:10)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ganache-cli/node_modules/source-map-support/source-map-support.js:461:21)
    at process.C.process.emit (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:29928)
    at process._fatalException (bootstrap_node.js:374:26)

```

## Your Environment
* Version used:
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux):
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by aakilfernandes** [comment]
Turns out this is actually originating in `support-map-support`

https://github.com/evanw/node-source-map-support/blob/master/source-map-support.js#L540-L556

Can you add `handleUncaughtExceptions: false` when installing `source-map-support`? Shimming the process.emit is going to have unintended downstream effects

**Comment by aakilfernandes** [comment]
Right now I'm doing this as a monkeypatch

```
const processEmit = process.emit
require('ganache-cli')
process.emit = function (error) {
  processEmit.apply(this, processEmit)
}

```

**Comment by davidmurdoch** [comment]
Thanks @aakilfernandes 	for opening the issue and tracking this down. Is there any way you can provide a minimal reproduction of the issue? I don't think ganache should be throwing an exception at all here, so the bug is likely that we aren't properly handling something.

**Comment by aakilfernandes** [comment]
@davidmurdoch Ganache isn't throwing an exception. A third party library is.

1. Third party library throws uncaught `Error` error
2. `source-map-support` intercepts uncaught `Error` error and throws uncaught `String` error
3. Mocha breaks (can't handle `String` errors)

Hopefully that makes sense

**Comment by davidmurdoch** [comment]
Hmm, I think in general we _do_ want source-map-support to handle uncaught exceptions so the exception's stack trace is properly mapped to the source. Disabling `handleUncaughtExceptions` may have some unintended consequences here.

I wonder if there if there is another workaround here.

**Comment by digulla** [comment]
I've tried to solve this by adding

  if (typeof(err) === 'string') {
    err = new Error(err);
  }

at the top of `Runner.prototype.uncaught = function(err) {` in line 711 of `node_modules/mocha/lib/runner.js`.

That at least makes the errors easier to read it still looks weird:

```
  1) Contract: Foo
       "before all" hook: prepare suite:
     Uncaught Error: abort({"name":"AssertionError","message":"Missing exception of type \"Error\"","showDiff":false,"stack":"AssertionError: Missing exception of type \"Error\"\n    at expectThrowsAsync ($PROJECT/test/config_test.ts:32:16)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)"}). Build with -s ASSERTIONS=1 for more info.
      at process.emit (node_modules/truffle/build/webpack:/~/source-map-support/source-map-support.js:465:1)
      at process._fatalException (internal/process/execution.js:123:25)
```

In my use case, I have `assert.fail()` in a helper function:

```
// Based on https://stackoverflow.com/a/56104568/34088
const getErrorTypeName = (errorType) => {
    let result = type(errorType);
    if (result === 'function') {
        result = errorType.name;
    }
    return result;
}

const expectThrowsAsync = async (method, errorType, errorMessage) => {
    let error = null;
    try {
        await method();
    } catch (err) {
        error = err
    }
    if (error) {
        if (typeof(errorType) === 'string') {
            expect(getErrorTypeName(error)).to.equal(errorType);
        } else {
            expect(error).to.be.an.instanceof(errorType);
        }
    } else {
        const typeName = getErrorTypeName(errorType);
        assert.fail(`Missing exception of type "${typeName}"`);
    }
    if (errorMessage) {
        expect(error.message).to.equal(errorMessage);
    }
}
```

Test looks like so:

```
    it("SenderAccess works for anyone else", async () => {
        const accessControl = await SenderAccess.new();
        const anyoneElse = accounts[1];

        //await accessControl.verify({from: anyoneElse}); // TODO This must fail
        expectThrowsAsync(() =>
            accessControl.verify({from: anyoneElse}),
            Error,
            "Returned error: VM Exception while processing transaction: revert You're not allowed to access this function"
        );
    });
```

and the contract is:

```
contract SenderAccess is AccessControl {
	address owner;
	constructor() public {
		owner = msg.sender;
	}

	function verify() public view {
		require(owner == msg.sender, "You're not allowed to access this function");
	}
}
```

Using truffle 5.1.0 with mocha 5.2.0.
