### ISSUE TITLE
evm_revert: Inconsistency between documentation and behaviour

### ISSUE THREAD

**Issue by anvacaru** [trufflesuite/ganache-cli#672]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

The [documentation](https://github.com/trufflesuite/ganache-core/blob/2e6304547c7c5620c11145f52e512642170cbdbd/README.md#custom-methods) for `evm_revert` mentions that *If no snapshot id is passed it will revert to the latest snapshot*.
## Current Behavior

When sending an `evm_revert` rpc request without a snapshot ID it will return an error message saying that the function requires exactly one argument:
```
{"id":1337,"jsonrpc":"2.0","error":{"message":"Incorrect number of arguments. Method 'evm_revert' requires exactly 1 arguments. Request specified 0 arguments: [null].","code":-32000,"data":{"stack":"Error: Incorrect number of arguments. Method 'evm_revert' requires exactly 1 arguments. Request specified 0 arguments: [null].\n    at b.handleRequest (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:564894)\n    at t (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:439244)\n    at a.handleRequest (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:563217)\n    at t (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:439244)\n    at c.f.handleRequest (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:556235)\n    at c.handleRequest (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:554061)\n    at t (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:439244)\n    at s.handleRequest (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:562231)\n    at t (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:439244)\n    at a.handleRequest (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:561678)\n    at t (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:439244)\n    at d._handleAsync (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:439280)\n    at Timeout._onTimeout (/home/anvacaru/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:438705)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)","name":"Error"}}}
```

## Steps to Reproduce (for bugs)

1. In a fresh terminal, run `npx ganache-cli`.
2. In another fresh terminal, send the following request:
```
curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"evm_revert","params":[]}' \
        http://localhost:8545
```

## Your Environment
* Version used: Ganache CLI v6.6.0 (ganache-core: 2.7.0)
* Version of Truffle/Remix/Other tools used: - 
* NodeJS Version: v10.16.0
* Operating System and version (include distro if Linux): Ubuntu 18.04.3 LTS
* Link to your project or repro gist: -
* Commit hash to use with above link for reproduction: -
* I intend to submit a pull request to fix this issue: [ ]

**Comment by wilwade** [comment]
I can confirm this is still happening for Ganache CLI v6.12.2 (ganache-core: 2.13.2)

Can someone tag which thing is wrong: the behavior or the documentation? I can maybe do a PR to fix it, but not sure which one should be fixed.

IMHO the behavior is wrong (or an additional method should be added to get the current stack of snapshots or clear all snapshots).
