### ISSUE TITLE
Performance regression in ganache-cli > 6.4.5

### ISSUE THREAD

**Issue by alcuadrado** [trufflesuite/ganache-cli#677]
I found a big performance regression in ganache-cli > 6.4.5. Some RPC requests are taking up to 19 seconds to finish. Most of them are `eth_call` calls, but sometimes `net_version` ones also get stuck.

## Expected Behavior

Ganache > 6.4.5 should have around the same performance than 6.4.5.

## Current Behavior

Some requests take much much longer.

## Steps to Reproduce (for bugs)

1. Clone this repo in that particular version: https://github.com/clovers-network/clovers-contracts/tree/53036b6d462c6e440a9e71360cd4fcf4ad49faed 
2. Install ganache-cli ` 6.4.5`.
3. Run the repo tests against ganache. Take note of the time spent by each test.
4. Install a newer ganache-cli, say ` 6.7.0`.
3. Run the repo tests against ganache. Take note of the time spent by each test. Some of them will be much larger.

## Your Environment
* Version used: 6.4.5, 6.5.1, 6.6.0, 6.7.0
* Version of Truffle/Remix/Other tools used: Truffle v4.1.13, Buidler 1.0.0-beta.10
* NodeJS Version: v8.16.0
* Operating System and version (include distro if Linux): MacOS 10.14.6 (18G87)
* Link to your project or repro gist: https://github.com/clovers-network/clovers-contracts/tree/53036b6d462c6e440a9e71360cd4fcf4ad49faed
* Commit hash to use with above link for reproduction: 53036b6d462c6e440a9e71360cd4fcf4ad49faed
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Can you expand on the `Run the repo tests against ganache. Take note of the time spent by each test.` step? I've manually updated the truffle config with a hardcoded mnemonic to point to a `ganache-cli@6.4.5` running with the same mnemonic on on 9545, but the tests seem to hang on `Contract: Clovers`.

**Comment by alcuadrado** [comment]
Ah, sorry @davidmurdoch, I opened this issue in a hurry and didn't notice that it was super incomplete.

Here are more details on how to reproduce it and how to notices this behavior.

```
pato@pmbp:clovers-contracts (53036b6 ✔)% uname -a
Darwin pmbp 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

pato@pmbp:clovers-contracts (53036b6 ✔)% which node
/Users/pato/.nvm/versions/node/v8.16.0/bin/node

pato@pmbp:clovers-contracts (53036b6 ✔)% npm --version
6.11.3

pato@pmbp:ganache-repro% git clone git@github.com:clovers-network/clovers-contracts.git

pato@pmbp:ganache-repro% cd clovers-contracts

pato@pmbp:clovers-contracts (master ✔)% git checkout 53036b6d462c6e440a9e71360cd4fcf4ad49faed

pato@pmbp:clovers-contracts (53036b6 ✔)% npm i

pato@pmbp:clovers-contracts (53036b6 *)% npx truffle --version
Truffle v4.1.13 - a development framework for Ethereum

pato@pmbp:clovers-contracts (53036b6 *)% npx ganache-cli --version
Ganache CLI v6.1.8 (ganache-core: 2.2.1)

pato@pmbp:clovers-contracts (53036b6 *)% npm i ganache-cli@6.4.5

pato@pmbp:clovers-contracts (53036b6 *)% npx ganache-cli --version
Ganache CLI v6.4.5 (ganache-core: 2.5.7)
```

Add this network to `truffle.js`:

```js
    reproduction: {
      host: "localhost",
      port: 8545,
      network_id: "*",
    },
```

```
pato@pmbp:clovers-contracts (53036b6 *)% npx ganache-cli # in another terminal

pato@pmbp:clovers-contracts (53036b6 *)% npx truffle --network reproduction test
```

All the tests should pass, but some of them are consistently somewhat slow. You can note that by looking at Mocha's execution time reporter. For example:

```
    CloversController.sol
      ✓ should convert correctly (3004ms)
```

```
  Contract: Reversi                                                       
    Reversi.sol                                                           
        reversiMock.logGame - 1748502                                     
                $0.35 @ 0.000000001 GWE & 200/USD                         
                $3.50 @ 0.00000001 GWE & 200/USD                          
      ✓ should get cost to play a game (2995ms)                           
      ✓ should play a valid game without error (2413ms)                   
      ✓ should play a valid game with empty squares without error (3302ms)
```      

At the same time, by looking at ganache-cli's terminal, you'll see that it get's
stuck (not printing output) in those tests.

So far, this is the expected behavior. Now follows the actual reproduction.

Kill your ganache-cli process, and execute this:

```
pato@pmbp:clovers-contracts (53036b6 *)% npm i ganache-cli@latest

pato@pmbp:clovers-contracts (53036b6 *)% npx ganache-cli --version
You can improve web3's peformance when running Node.js versions older than 10.5.0 by installing the (deprecated) scrypt package in your project
Ganache CLI v6.7.0 (ganache-core: 2.8.0)

pato@pmbp:clovers-contracts (53036b6 *)% npx ganache-cli # in another terminal
```

The tests that were slow are now consistently 3-7x slower. 

```
    CloversController.sol
      ✓ should convert correctly (8880ms)
```

```
 Contract: Reversi
    Reversi.sol
        reversiMock.logGame - 1748502
                $0.35 @ 0.000000001 GWE & 200/USD
                $3.50 @ 0.00000001 GWE & 200/USD
      ✓ should get cost to play a game (8861ms)
      ✓ should play a valid game without error (8574ms)
      ✓ should play a valid game with empty squares without error (20613ms)
      ✓ should fail when plaing empty moves game
      ✓ should fail when plaing game where last move is invalid (8284ms)
```


The same behavior from ganache-cli's output can be observed.

Some tests also fail, but I suspect this is because of the tests having temporal
dependencies between each other.

```
  1) Contract: Clovers
       CloversController.sol
         should make sure it is verified after blocks increase:
     AssertionError: clover wasn't verified when it should have been already
      at Context.<anonymous> (test/CloversController.test.js:1109:7)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  2) Contract: Clovers
       CloversController.sol
         should make sure reward was received:
     BigNumber Error: gt() not a number: undefined
      at raise (node_modules/truffle/build/webpack:/~/bignumber.js/bignumber.js:1177:1)
      at node_modules/truffle/build/webpack:/~/bignumber.js/bignumber.js:1165:1
      at new BigNumber (node_modules/truffle/build/webpack:/~/bignumber.js/bignumber.js:193:1)
      at BigNumber.P.greaterThan.P.gt (node_modules/truffle/build/webpack:/~/bignumber.js/bignumber.js:1490:1)
      at Context.<anonymous> (test/CloversController.test.js:1161:22)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

Re-running the tests with and without restarting ganache-cli gives the same results.
