### ISSUE TITLE
ganache-cli 6.7.0 - Could not connect to your Ethereum client with the following parameters 

### ISSUE THREAD

**Issue by abhayks1** [trufflesuite/ganache-cli#702]
Hi Team,

Our travis tests are running ganache-cli version `6.7.0`.
ganache-cli is behaving strangely. Issue we are facing is that ganache getting killed abruptly.
After restarting the build multiple times, test passes. 
Below is build url: https://travis-ci.org/mosaicdao/mosaic-1/builds/620990322
```
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575530243622
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
  Error:     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:224:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:34:1)
      at Context.beforeEach (test/reputation/slash.js:39:31)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

Below is the truffle config:

```
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      network_id: '*',
      port: 8545,
      gas: 12000000,
      gasPrice: 0x01,
    },
  },
  compilers: {
    solc: {
      version: '0.5.8',
      settings: {
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
    },
  },
  mocha: {
    enableTimeouts: false
  },
};
```

Ganache is being started with below command:
```
./node_modules/.bin/ganache-cli" \
    --accounts=1000 \
    --defaultBalanceEther=10000 \
    --gasLimit 0xfffffffffff
```
Below is how we are creating our web3 object:
```
const web3 = new Web3('http://localhost:8545');
```
How can above issue be fixed?

**Comment by abhayks1** [comment]
Could this happen because of too many connections on Ganache? Please help us with the solution.

**Comment by cgewecke** [comment]
@abhayks1 Am investigating this at the moment - it's possible it's a problem with Web3 >= 1.2.2 

Is it fixed if you try Web3 1.2.1 and Truffle 5.0.43?

**Comment by abhayks1** [comment]
@cgewecke test passes with below package versions:
```
"ganache-cli": "6.8.1-beta.0",
"truffle": "5.0.43",
"web3": "1.2.1",
```
Can you please the issue in more details?

**Comment by elenadimitrova** [comment]
I am experiencing this issue when testing the [argent-contracts](https://github.com/argentlabs/argent-contracts/tree/experiment/migrate-to-truffle). There are 420 tests in suite and those start failing with 
```
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8545
    - network_id > 1597649375983
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
```
and ganache starts emitting a lot of `getBlockByNumber` events. 

This happens with `truffle 5.1.52` but not with `5.1.48`. Running on `ganache-cli` `6.12.1`.

**Comment by MaxFeldman1** [comment]
This just started happening for me when I load a transaction into truffle debug after my project reached some size, it does not happen when I debug transactions from smaller projects

I don't know that it has anything to do with the amount/size of tests perhaps it has something to do with the total amount of bytecode/abi complexity within the project

**Comment by MaxFeldman1** [comment]
update I tried with truffle 5.1.48 and still received the same error

**Comment by 2608027102** [comment]
I also get this error when I perform multiple tests by `truffle test`.

```
Truffle v5.1.51 (core: 5.1.51)
Solidity - 0.4.24 (solc-js)
Node v12.16.1
Web3.js v1.2.9

Ganache CLI v6.12.1 (ganache-core: 2.13.1)
```

**Comment by josh-richardson** [comment]
I'm also encountering this during truffle tests on a large codebase which I can't currently share, but should be able to in the next month. Strangely, it only happens with Solidity 0.6. If we compile using Solidity 0.5 (with syntactic changes only, no functionality changed other than keywords), everything seems to work fine. If I run all our tests (`npx truffle test`) this issue occurs frequently, however if I run each single test in isolation (`npx truffle test <test/file.test.js>`), everything passes as expected.

Truffle v5.1.24 (core: 5.1.24)
Solidity - 0.6.12 (solc-js)
Node v10.23.0
Web3.js v1.2.1


**Edit**: I can confirm that after upgrading truffle & ganache-cli & implementing the fix as suggested in https://github.com/trufflesuite/truffle/issues/2688#issuecomment-736639231, this issue no longer seems to occur in my codebase.

**Comment by usermanoj** [comment]
Hi Guys,

I am trying to migrate a contract as per [https://www.trufflesuite.com/tutorials/pet-shop] and getting an error
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > *

I have added "disableConfirmationListener: true" in truffle-config.js file as per the screenshot too

![image](https://user-images.githubusercontent.com/36362085/110194782-62df3200-7e75-11eb-84d4-dd612080f80d.png)

Ganache is up & running too with enclosed config
![image](https://user-images.githubusercontent.com/36362085/110194806-9ae67500-7e75-11eb-9568-eb13f8c46961.png)

Truffle v5.1.66 (core: 5.1.66)
Node v10.23.3 

Please advise. Thanks.

P.S. - Please take note that I am new to Github and Blockchain

**Comment by thomasender** [comment]
any solutions for this? having the same problem, appearing after adding another test file

**Comment by ntefa** [comment]
I have the same problem. Truffle does work with Ganache GUI but not with the cli, even though the config file has been adjusted.

**Comment by julien51** [comment]
Same for us here @unlock-protocol. 
It seems quite transient where some CI build pass, and other fail abruptly. Tried with different block times, but no luck.

**Comment by PfanP** [comment]
We still don't have any update for this issue?
