### ISSUE TITLE
sporadic ECONNRESET when running for a long time

### ISSUE THREAD

**Issue by wjmelements** [trufflesuite/ganache-cli#703]
Using ganache-cli 6.8.1-beta.0. Also happens on ganache-cli 6.8.0-istanbul.0. It seems to use ganache-core-sc 2.7.0-sc.0.

The error is
```Invalid JSON RPC response: "Error: connect ETIMEDOUT 127.0.0.1:8545\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"```

The truffle mocha tests run fine for the first 10 minutes or so but then the tests start to take longer and fail sporadically, sometimes mid-test and sometimes in beforeEach.

The early tests take 44-500ms.
![Screen Shot 2019-12-05 at 5 41 44 PM](https://user-images.githubusercontent.com/799573/70288507-be100980-1786-11ea-8cfa-ffd2fd23816e.png)

The tests right before the first failure start to take longer, but less than 500
![Screen Shot 2019-12-05 at 5 42 10 PM](https://user-images.githubusercontent.com/799573/70288562-e7309a00-1786-11ea-9962-95801eda62e0.png)
ms

After the first connection reset, the tests spike above 9000ms, and I have seen them as high as 27000ms.
![Screen Shot 2019-12-05 at 5 42 36 PM](https://user-images.githubusercontent.com/799573/70288593-f44d8900-1786-11ea-96a1-21c44e8299cb.png)

The increase explodes slowly, and did not happen in prior versions, though we were upgrading from ganache-cli 6.1.0.

**Comment by wjmelements** [comment]
I forgot to include a screenshot of the error
![Screen Shot 2019-12-05 at 6 00 43 PM](https://user-images.githubusercontent.com/799573/70289319-38da2400-1789-11ea-9a25-c9a85bd45ea3.png)

**Comment by wjmelements** [comment]
I have also seen this error twice, though I think it's unrelated because it doesn't happen every time.

```
TypeError: this.removeListener is not a function
    at Object.receipt (~/work/true-currencies/node_modules/truffle/build/webpack:/packages/contract/lib/handlers.js:138:1)
    at Function.start (~/work/true-currencies/node_modules/truffle/build/webpack:/packages/contract/lib/override.js:53:1)
```

**Comment by wjmelements** [comment]
New record, 229986ms
![Screen Shot 2019-12-05 at 6 26 00 PM](https://user-images.githubusercontent.com/799573/70290438-b5223680-178c-11ea-9246-635d7d0139f8.png)

**Comment by wjmelements** [comment]
The failures do not coincide with a dramatic increase in memory, but do coincide with a dramatic drop in CPU utilization from the ganache process.

**Comment by wjmelements** [comment]
We are working around by running only one file at a time.

**Comment by wjmelements** [comment]
The aforementioned workaround worked without restarting ganache, so I think this is a truffle issue.

**Comment by nicholasjpaterno** [comment]
@wjmelements Thanks for taking the time to create and update this issue!  I'm going to cc @CruzMolina and @eggplantzzz for some extra eyes from the truffle side.  Thanks again!

**Comment by CruzMolina** [comment]
Hey @wjmelements , which version of truffle and node are you using?

**Comment by wjmelements** [comment]
@CruzMolina 5.1.2

**Comment by wjmelements** [comment]
I see ganache and truffle both run in node but I don't see node among the dependencies. My globally-installed node version is v10.14.1.

**Comment by CruzMolina** [comment]
Thanks @wjmelements ! Can you provide a repo for reproduction/debugging purposes? If not, can you try running your tests against truffle@5.0.43 and see if the problem is resolved?

**Comment by wjmelements** [comment]
https://github.com/trusttoken/true-currencies/commit/5eefff87b678b97985fd150f642853d650199933
npm test at this commit fails for the reason cited in this issue with the
output screenshotted. Note the repo setup instructions in the readme,
particularly the git submodule + npm install.
I believe it also failed for 5.0.44, which is the truffle version at that
commit.

**Comment by CruzMolina** [comment]
Thanks! If it's the same issue I think it is, 5.0.44 should fail, but not 5.0.43. Will check this out and get back to you.

**Comment by CruzMolina** [comment]
Sweet. All tests passed using 5.0.43 on that commit.

It's very likely that this issue is resolved by trufflesuite/truffle#2663.

**Comment by CruzMolina** [comment]
Yup, ran into the same issues as you did @wjmelements when running the tests against 5.0.44.

There should be a new truffle release by the end of this week that solves this, meanwhile 5.0.43 should be good to pin to 🤞.

**Comment by wjmelements** [comment]
Thanks, will do!
