### ISSUE TITLE
eth_getTransactionByHash failing with "Error: Number can only safely store up to 53 bits" when using ganache-cli with fork

### ISSUE THREAD

**Issue by acryptosx** [trufflesuite/ganache-cli#818]
This works fine when connected directly to the un-forked node, but when connected to the local forked ganache-cli node, trying to get a transaction results in:

truffle(bscforktest)> web3.eth.getTransaction('0x023d62577aab3260d6328838ef332216286495b171494b798c74fc7818a94e58')
Uncaught Error: Returned error: Number can only safely store up to 53 bits
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:554:1)
    at WebSocketConnection.EventEmitter.emit (domain.js:486:12)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:205:1)
    at W3CWebSocket.onMessage (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:234:1)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/yaeti/lib/EventTarget.js:115:1)
    at WebsocketProvider._onMessage (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:118:1)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:133:1
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:170:1
    at Object.ErrorResponse (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)

ganache-cli is started with:
ganache-cli --fork wss://bsc-ws-node.nariox.org:443

Version: Ganache CLI v6.12.2 (ganache-core: 2.13.2)

**Comment by acryptosx** [comment]
I loaded up vanilla web3 and tried to getTransaction:

Error: Returned error: Number can only safely store up to 53 bits
    at Object.ErrorResponse (/Users/xx/xx/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at Object.callback (/Users/xx/xx/node_modules/web3-core-requestmanager/lib/index.js:291:36)
    at /Users/xx/xx/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/Users/xx/xx/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/xx/xx/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/Users/xx/xx/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/xx/xx/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/Users/xx/xx/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/xx/xx/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  data: {
    stack: 'Error: Number can only safely store up to 53 bits\n' +
      '    at assert (/usr/local/lib/node_modules/ganache-cli/node_modules/bn.js/lib/bn.js:6:21)\n' +
      '    at BN.toNumber (/usr/local/lib/node_modules/ganache-cli/node_modules/bn.js/lib/bn.js:506:7)\n' +
      '    at Object.hexToNumber (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:50:26693)\n' +
      '    at s (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2115124)\n' +
      '    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2118807\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at d.outputBlockFormatter [as outputFormatter] (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2118761)\n' +
      '    at d.formatOutput (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:108251)\n' +
      '    at s (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:113913)\n' +
      '    at a (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2108976)\n' +
      '    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2093154',
    name: 'Error'
  }
}

**Comment by acryptosx** [comment]
here are steps to reproduce:

1. run: ganache-cli --fork https://bsc-dataseed.binance.org/

2. run script: https://gist.github.com/acryptosx/6b71e1e767602f9b6905d8270ca77b22

**Comment by eyooooo** [comment]
Bumping this issue - i also get weird errors like this. 

this fails in web3
`web3.eth.getTransaction('0x6971eb54baa66b420b6c58172bd1ff17e1119e2c11cfdc92c45eb920675c1bf6')`

with error
```
> web3.eth.getTransaction('0x6971eb54baa66b420b6c58172bd1ff17e1119e2c11cfdc92c45eb920675c1bf6')
Promise { <pending> }
> (node:360) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
    at assert (/home/dork/crapcrap/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/home/dork/crapcrap/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (/home/dork/crapcrap/node_modules/web3-utils/lib/utils.js:208:24)
    at Method.outputTransactionFormatter [as outputFormatter] (/home/dork/crapcrap/node_modules/web3-core-helpers/lib/formatters.js:204:20)
    at Method.formatOutput (/home/dork/crapcrap/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/dork/crapcrap/node_modules/web3-core-method/lib/index.js:523:33)
    at Object.callback (/home/dork/crapcrap/node_modules/web3-core-requestmanager/lib/index.js:308:9)
    at /home/dork/crapcrap/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/home/dork/crapcrap/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/dork/crapcrap/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/dork/crapcrap/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/dork/crapcrap/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:529:15)
    at WebSocketConnection.processFrame (/home/dork/crapcrap/node_modules/websocket/lib/WebSocketConnection.js:554:26)
(node:360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

yet, directly from the GETH console, this has no issues

```
> eth.getTransaction('0x6971eb54baa66b420b6c58172bd1ff17e1119e2c11cfdc92c45eb920675c1bf6')
{
  blockHash: "0xabd32259e01f7f37854c0c95ebbeaaf04c18eca5fa059747f693d350b8bc28ed",
  blockNumber: 363,
  from: "0x6488aa4d1955ee33403f8ccb1d4de5fb97c7ade2",
  gas: 9223372036854776000,
  gasPrice: 0,
  hash: "0x6971eb54baa66b420b6c58172bd1ff17e1119e2c11cfdc92c45eb920675c1bf6",
  input: "0x",
  nonce: 1,
  r: "0x292353baf23b2fd7cda3788057fbb3acdd16bf4ff979d32b8385318627dd05ef",
  s: "0x23fbad60c770523f1efc4aca78360cc2ddab8bbaeb0135212150c5333d61c74e",
  to: "0x0000000000000000000000000000000000001002",
  transactionIndex: 1,
  v: "0x94",
  value: 110356250000000
}
```

**Comment by AgusVelez5** [comment]
Hi guys, I have the same issue
I wrote a script that review the data of all transactions on the latest block but fails when execute:
`web3.eth.getTransaction(<hash of last tx of the block>)`
Do you have any update?

**Comment by artman325** [comment]
I have the same issue.
Do you have any update?

**Comment by cryptobrokering** [comment]
Similar error here, when trying to debug a Tx on the BSC Mainnet fork with ganache-cli and truffle, I get the following:
```
Starting Truffle Debugger...
Error: Number can only safely store up to 53 bits
    at /Users/tyler/projects/truffle/packages/debugger/lib/web3/adapter.js:29:13
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/truffle/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/truffle/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
- Compiling your contracts...
✔ Compiling your contracts...
```

**Comment by nonseodion** [comment]
I get the same error when I use ht ganache-cli with fork and OpenGsn Relay service.

**Comment by mrwillis** [comment]
Anyone have a workaround for this?
