### ISSUE TITLE
Large debug traces overflow JSON.stringify

### ISSUE THREAD

**Issue by jeffywu** [trufflesuite/ganache-cli#829]
When issuing `debug_traceTransaction` requests it's possible that the result is larger than the limits of what JSON.stringify can handle. You can see errors such as this when it occurs:

```
debug_traceTransaction
   > {
   >   "jsonrpc": "2.0",
   >   "method": "debug_traceTransaction",
   >   "params": [
   >     "0xbf2ff613a3fdaa6eb1090a7835c1f92bca31d8ed49128201b506504652d30331",
   >     {
   >       "disableStorage": true
   >     }
   >   ],
   >   "id": 352
   > }
(node:437911) UnhandledPromiseRejectionWarning: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Object.a [as callback] (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:14893)
    at e.engine.sendAsync (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:15708)
    at /home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:64767
    at /home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:31564
    at p (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:31221)
    at /home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:31274
    at t.default (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:166358)
    at /home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:32188
    at Object.o [as callback] (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:64608)
    at n (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:212585)
    at /home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:54514
    at N (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:51818)
    at w.processBlock (/home/jwu/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:51971)
(node:437911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 117)
(node:437911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected Behavior

Expected behavior is that the debug trace is properly returned

## Current Behavior

See stacktrace above.

## Possible Solution

Use a library to handle large JSON objects: 
https://www.npmjs.com/package/big-json
https://www.npmjs.com/package/JSONStream <= this one is very popular but hasn't been updated in awhile, probably not necessary to update frequently for something like this.
https://www.npmjs.com/package/stream-json

## Steps to Reproduce (for bugs)

Not sure if there are public contracts that cause this issue but I don't have any contracts that I can attach that do this already. Any sufficiently large gas transaction would cause this error I think.

## Context

I am using eth-brownie and it uses debug_traceTransaction to produce test coverage reports. This is blocking me from getting a full test coverage report since some transactions will error out at this point.

## Your Environment
ganache-cli --version        
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
node --version
v10.17.0
OS: linux

* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by jeffywu** [comment]
Let me know if this is something the team has run into before, I'm keen to get this fixed so happy to help.

**Comment by jeffywu** [comment]
Related to this issue: https://github.com/trufflesuite/ganache-core/issues/332
